### PR TITLE
Add TravisCI integration

### PR DESCRIPTION
**Pull request by gnclmorais**
Following [TravisCI documentation](https://docs.travis-ci.com/user/getting-started/) in order to add automatic tests. ✅

### CODE REVIEW

**Comment by vicchi** [comment]
Merged. Thanks @gnclmorais

**Comment by gnclmorais** [comment]
No problem! I just realised this will fail until the tests as merged, though… 😅  So I’ll take care of [you request](https://github.com/vicchi/node-getpocket/pull/3#issuecomment-314358216) as soon as possible! ⚡️

**Comment by vicchi** [comment]
That's a very good point - I obviously need more coffee this morning!

**Comment by gnclmorais** [comment]
Me too! ☕️ ✖️ 💯

**Comment by gnclmorais** [comment]
Hey @vicchi, I forgot to explain, but this PR adds the necessary TravisCI configuration to the repository for it to be able to run automated tests. **However**, each user needs to enable it for its own repository. I enabled it for `gnclmorais/node-getpocket`, but since I don’t have access to this repo, you would have to do it for `vicchi/node-getpocket`. It’s simple, you just need to follow steps **1** and **2** of [this guide](https://docs.travis-ci.com/user/getting-started/) (since this PR takes care of the other steps). 😃

**Comment by vicchi** [comment]
@gnclmorais - don't worry - I'd already made that assumption. I just haven't had time (yet) to enable Travis for this repo (the day job gets in the way sometimes!)

**Comment by vicchi** [comment]
And now it's up and running - https://travis-ci.org/vicchi/node-getpocket

**Comment by gnclmorais** [comment]
Fantastic! I have a following PR then! 😁

**Pull request merged**
